---
api:
  build: .
  ports:
    - "3000"
  volumes:
    - ./:/src
db:
  image: library/mariadb:latest
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: toor
  volumes:
    - .data/mariadb:/var/lib/mysql

